### ISSUE TITLE
False positives (possibly due to case-sensitive searches)

### ISSUE THREAD

**Issue by freshgruts** [ulisesantana/obsidian-pending-notes#3]
This plugin identified many ‘pending’ notes in my vault which weren’t pending—I already had notes with those titles. I believe this was due to the plugin carrying out case-sensitive searches, whereas Obsidian’s [[WikiLinks]] are case-insensitive. Until I realised there was a problem, this resulted in me creating several duplicate notes.

**Comment by ulisesantana** [comment]
Thank you for opening the issue, I really appreciate it. As you suggested the problem was related to case-sensitive stuff. Right now is not going to show you any note that is already created, but has some difference related with case-sensitive. 

However, if you have not created yet a note, but you have pending notes with differences related with cases, all of them are going to be showed. Still, if you create one of these notes by clicking on it, it will be created and the other ones will be hidden from the pending notes list.

This is fixed on [version 0.5.3](https://github.com/ulisesantana/obsidian-pending-notes/releases/tag/0.5.3).
